# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'FSLABScli Installer'
description: 'Install a specific FSLABScli version'
author: 'ForesightMiningSoftwareCorporation'
branding:
  icon: 'fast-forward'
  color: 'purple'
inputs:
  version:
    description: 'Specify FSLABScli version to use. Accepted values are any FSLABScli version'
    required: false
    default: 0.3.6
  token:
    description: Github Token to fetch private binaries
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
