---
name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  # unit tests
  units:
    name: Test Javascript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Node.js 16.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 16.x
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Lint Test
      run: npm run lint

#    - name: Run tests
#      run: npm test

  e2e:
    name: Test fslabscli Github Action
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4


      - uses: tibdex/github-app-token@v2.1.0
        id: generate_token
        with:
          app_id: ${{ secrets.FMSC_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.FMSC_BOT_GITHUB_APP_PRIVATE_KEY }}

      - name: Install FSLABScli
        uses: ./
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Test local action without install-only
        run:  fslabscli generate-release-workflow --output .github/workflows/release.yml
