---
name: updatecli

on:
  workflow_dispatch:
  push:
    branches:
      - v1
  schedule:
    # Run once a day
    - cron: '*/10 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v2.1.0
        id: generate_token
        if: steps.commit.outputs.diff
        with:
          app_id: ${{ secrets.FMSC_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.FMSC_BOT_GITHUB_APP_PRIVATE_KEY }}

      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"

      - name: "Run updatecli in dryrun"
        run: "updatecli diff --config ./updatecli/updatecli.d --experimental --clean=true"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: "Run updatecli"
        if: github.ref == 'refs/heads/v2'
        run: "updatecli apply --config ./updatecli/updatecli.d --experimental --clean=true"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

